### ISSUE TITLE
Couldn't listen on lowdiff.ltcrabbit.com:3333:

### ISSUE THREAD

**Issue by hugo4715** [slush0/stratum-mining-proxy#80]
When I start the proxy (python mining_proxy.py -sh lowdiff.ltcrabbit.com -cp 80 -cu USER -cp PASSWORD), I receive the error: 

2015-10-11 18:57:21,576 INFO proxy mining_proxy.on_connect # Subscribing for mining jobs
2015-10-11 18:57:21,634 WARNING proxy mining_proxy.on_connect # Authorizing custom user USER, password PASSWORD
Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Twisted-15.4.0-py2.7-linux-armv7l.egg/twisted/internet/defer.py", line 393, in callback
    self._startRunCallbacks(result)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-15.4.0-py2.7-linux-armv7l.egg/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-15.4.0-py2.7-linux-armv7l.egg/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-15.4.0-py2.7-linux-armv7l.egg/twisted/internet/defer.py", line 1184, in gotResult
    _inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/Twisted-15.4.0-py2.7-linux-armv7l.egg/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "mining_proxy.py", line 257, in main
    reactor.listenTCP(args.stratum_port, SocketTransportFactory(debug=False, event_handler=ServiceEventHandler), interface=args.stratum_host)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-15.4.0-py2.7-linux-armv7l.egg/twisted/internet/posixbase.py", line 478, in listenTCP
    p.startListening()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-15.4.0-py2.7-linux-armv7l.egg/twisted/internet/tcp.py", line 984, in startListening
    raise CannotListenError(self.interface, self.port, le)
twisted.internet.error.CannotListenError: Couldn't listen on lowdiff.ltcrabbit.com:3333: [Errno 99] Cannot assign requested address.
2015-10-11 18:57:21,698 INFO proxy client_service.handle_event # Setting new difficulty: 256

I really don't know how to solve this issue.

**Comment by hugo4715** [comment]
Sorry, I realize I was just using bad arguments, my bad :p
