### ISSUE TITLE
Can not build it in OSX

### ISSUE THREAD

**Issue by chinanoahli** [slush0/stratum-mining-proxy#82]
This is my build log
```
sudo python setup.py install                                                                                              <! 4743 <7:38:49
running install
running bdist_egg
running egg_info
writing requirements to stratum_mining_proxy.egg-info/requires.txt
writing stratum_mining_proxy.egg-info/PKG-INFO
writing top-level names to stratum_mining_proxy.egg-info/top_level.txt
writing dependency_links to stratum_mining_proxy.egg-info/dependency_links.txt
writing requirements to stratum_mining_proxy.egg-info/requires.txt
writing stratum_mining_proxy.egg-info/PKG-INFO
writing top-level names to stratum_mining_proxy.egg-info/top_level.txt
writing dependency_links to stratum_mining_proxy.egg-info/dependency_links.txt
reading manifest file 'stratum_mining_proxy.egg-info/SOURCES.txt'
writing manifest file 'stratum_mining_proxy.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.11-x86_64/egg
running install_lib
running build_py
running build_ext
building 'midstate' extension
clang -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/include/python2.7 -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c midstatec/midstatemodule.c -o build/temp.macosx-10.11-x86_64-2.7/midstatec/midstatemodule.o -march=native -Wall -funroll-all-loops -O3 -fstrict-aliasing -Wall -std=c99 -fPIC -shared
clang: warning: optimization flag '-funroll-all-loops' is not supported
clang: warning: argument unused during compilation: '-shared'
midstatec/midstatemodule.c:84:39: warning: duplicate 'const' declaration specifier [-Wduplicate-decl-specifier]
        update_state(&state, (const uint32_t const *) data);
                                             ^
1 warning generated.
clang -bundle -undefined dynamic_lookup build/temp.macosx-10.11-x86_64-2.7/midstatec/midstatemodule.o -L/usr/local/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/sqlite/lib -lpython2.7 -o build/lib.macosx-10.11-x86_64-2.7/midstate.so -Wl,-O1 -Wl,--as-needed
ld: unknown option: -O1
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'clang' failed with exit status 1
```

**Comment by fbaquero** [comment]
I have the same issue. ¿Do you solved it?

**Comment by bapohka** [comment]
slush0-stratum-mining-proxy-e237fe3 user$ sudo python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to stratum_mining_proxy.egg-info/requires.txt
writing stratum_mining_proxy.egg-info/PKG-INFO
writing top-level names to stratum_mining_proxy.egg-info/top_level.txt
writing dependency_links to stratum_mining_proxy.egg-info/dependency_links.txt
writing requirements to stratum_mining_proxy.egg-info/requires.txt
writing stratum_mining_proxy.egg-info/PKG-INFO
writing top-level names to stratum_mining_proxy.egg-info/top_level.txt
writing dependency_links to stratum_mining_proxy.egg-info/dependency_links.txt
reading manifest file 'stratum_mining_proxy.egg-info/SOURCES.txt'
writing manifest file 'stratum_mining_proxy.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.12-intel/egg
running install_lib
running build_py
running build_ext
building 'midstate' extension
cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -I/usr/include/python2.7 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c midstatec/midstatemodule.c -o build/temp.macosx-10.12-intel-2.7/midstatec/midstatemodule.o -march=native -Wall -funroll-all-loops -O3 -fstrict-aliasing -Wall -std=c99 -fPIC -shared
clang: warning: optimization flag '-funroll-all-loops' is not supported [-Wignored-optimization-argument]
clang: warning: optimization flag '-funroll-all-loops' is not supported [-Wignored-optimization-argument]
clang: warning: argument unused during compilation: '-shared' [-Wunused-command-line-argument]
midstatec/midstatemodule.c:84:39: warning: duplicate 'const' declaration specifier
      [-Wduplicate-decl-specifier]
        update_state(&state, (const uint32_t const *) data);
                                             ^
1 warning generated.
midstatec/midstatemodule.c:84:39: warning: duplicate 'const' declaration specifier
      [-Wduplicate-decl-specifier]
        update_state(&state, (const uint32_t const *) data);
                                             ^
1 warning generated.
cc -bundle -undefined dynamic_lookup -arch x86_64 -arch i386 -Wl,-F. build/temp.macosx-10.12-intel-2.7/midstatec/midstatemodule.o -lpython2.7 -o build/lib.macosx-10.12-intel-2.7/midstate.so -Wl,-O1 -Wl,--as-needed
ld: unknown option: -O1
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'cc' failed with exit status 1

**Comment by bapohka** [comment]
but i have another problem on run 

sudo python mining_proxy.py
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/zope/__init__.py:3: UserWarning: Module twisted was already imported from /Library/Python/2.7/site-packages/Twisted-17.9.0rc1-py2.7-macosx-10.12-intel.egg/twisted/__init__.pyc, but /Library/Python/2.7/site-packages/autobahn-17.9.2-py2.7.egg is being added to sys.path
  import pkg_resources
Traceback (most recent call last):
  File "mining_proxy.py", line 67, in <module>
    from twisted.internet import reactor, defer
  File "/Library/Python/2.7/site-packages/Twisted-17.9.0rc1-py2.7-macosx-10.12-intel.egg/twisted/internet/reactor.py", line 38, in <module>
    from twisted.internet import default
  File "/Library/Python/2.7/site-packages/Twisted-17.9.0rc1-py2.7-macosx-10.12-intel.egg/twisted/internet/default.py", line 56, in <module>
    install = _getInstallFunction(platform)
  File "/Library/Python/2.7/site-packages/Twisted-17.9.0rc1-py2.7-macosx-10.12-intel.egg/twisted/internet/default.py", line 50, in _getInstallFunction
    from twisted.internet.selectreactor import install
  File "/Library/Python/2.7/site-packages/Twisted-17.9.0rc1-py2.7-macosx-10.12-intel.egg/twisted/internet/selectreactor.py", line 18, in <module>
    from twisted.internet import posixbase
  File "/Library/Python/2.7/site-packages/Twisted-17.9.0rc1-py2.7-macosx-10.12-intel.egg/twisted/internet/posixbase.py", line 18, in <module>
    from twisted.internet import error, udp, tcp
  File "/Library/Python/2.7/site-packages/Twisted-17.9.0rc1-py2.7-macosx-10.12-intel.egg/twisted/internet/tcp.py", line 28, in <module>
    from twisted.internet._newtls import (
  File "/Library/Python/2.7/site-packages/Twisted-17.9.0rc1-py2.7-macosx-10.12-intel.egg/twisted/internet/_newtls.py", line 21, in <module>
    from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
  File "/Library/Python/2.7/site-packages/Twisted-17.9.0rc1-py2.7-macosx-10.12-intel.egg/twisted/protocols/tls.py", line 63, in <module>
    from twisted.internet._sslverify import _setAcceptableProtocols
  File "/Library/Python/2.7/site-packages/Twisted-17.9.0rc1-py2.7-macosx-10.12-intel.egg/twisted/internet/_sslverify.py", line 38, in <module>
    TLSVersion.TLSv1_1: SSL.OP_NO_TLSv1_1,
AttributeError: 'module' object has no attribute 'OP_NO_TLSv1_1'

**Comment by brucefeynman** [comment]
I have the same issue here on mac os
