### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by bsmith18** [slush0/stratum-mining-proxy#86]
I tried to set the default recursion limit higher than 999 by adding `sys.setrecursionlimit(999999)` to setup.py but I still get the same error. 
```
RuntimeError: maximum recursion depth exceeded
./slush0-stratum-mining-proxy-e237fe3/distribute-0.6.28-py2.7.egg
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    use_setuptools()
  File "./slush0-stratum-mining-proxy-e237fe3/distribute_setup.py", line 145, in use_setuptools
    return _do_download(version, download_base, to_dir, download_delay)
  File "./slush0-stratum-mining-proxy-e237fe3/distribute_setup.py", line 125, in _do_download
    _build_egg(egg, tarball, to_dir)
  File ./slush0-stratum-mining-proxy-e237fe3/distribute_setup.py", line 116, in _build_egg
    raise IOError('Could not build the egg.')
IOError: Could not build the egg.
```
Any suggestions?

**Comment by svetbg** [comment]
I am stuck on the same error, is there any solution for it?

**Comment by Jacob201311** [comment]
me neither
