### ISSUE TITLE
reliance on twisted results in inability to install stratum-mining proxy

### ISSUE THREAD

**Issue by steowens** [slush0/stratum-mining-proxy#95]
I commented on another issue opened in Feb by someone else.  Then went looking for a work around.  At any rate the developers at Twisted seem to be too busy to take bug reports and there are definately problems installing that package.  I suspect it is something cached somewhere as mentioned in the following output.  But your project will not install because of this and I am not the only one faced with this problem:
$ pip install twisted
Collecting twisted
  Using cached https://files.pythonhosted.org/packages/5d/0e/a72d85a55761c2c3ff1cb968143a2fd5f360220779ed90e0fadf4106d4f2/Twisted-18.9.0.tar.bz2
    Complete output from command python setup.py egg_info:
    Couldn't find index page for 'twisted' (maybe misspelled?)
    No local packages or download links found for twisted>=16.4.0
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-SycYjI/twisted/setup.py", line 20, in <module>
        setuptools.setup(**_setup["getSetupArgs"]())
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.28-py2.7.egg/setuptools/dist.py", line 221, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.28-py2.7.egg/setuptools/dist.py", line 245, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 580, in resolve
        dist = best[req.key] = env.best_match(req, self, installer)
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 825, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 837, in obtain
        return installer(requirement)
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.28-py2.7.egg/setuptools/dist.py", line 294, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.28-py2.7.egg/setuptools/command/easy_install.py", line 592, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('twisted>=16.4.0')
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-SycYjI/twisted/

When you follow your instructions on the readme we get: 

sudo easy_install stratum
Searching for stratum
Reading http://pypi.python.org/simple/stratum/
Couldn't find index page for 'stratum' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading http://pypi.python.org/simple/
No local packages or download links found for stratum
error: Could not find suitable distribution for Requirement.parse('stratum')
steve@miner-1:~/stratum-mining-proxy$ sudo python setup.py develop -i https://pypi.python.org/simple/
/home/steve/stratum-mining-proxy/distribute_setup.py:139: UserWarning: Module distribute_setup was already imported from /home/steve/stratum-mining-proxy/distribute_setup.pyc, but /usr/local/lib/python2.7/dist-packages is being added to sys.path
  import pkg_resources
running develop
Checking .pth file support in /usr/local/lib/python2.7/dist-packages/
/usr/bin/python -E -c pass
TEST PASSED: /usr/local/lib/python2.7/dist-packages/ appears to support .pth files
running egg_info
writing requirements to stratum_mining_proxy.egg-info/requires.txt
writing stratum_mining_proxy.egg-info/PKG-INFO
writing top-level names to stratum_mining_proxy.egg-info/top_level.txt
writing dependency_links to stratum_mining_proxy.egg-info/dependency_links.txt
reading manifest file 'stratum_mining_proxy.egg-info/SOURCES.txt'
writing manifest file 'stratum_mining_proxy.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-2.7/midstate.so -> 
Creating /usr/local/lib/python2.7/dist-packages/stratum-mining-proxy.egg-link (link to .)
stratum-mining-proxy 1.5.7 is already the active version in easy-install.pth
Installing mining_proxy.py script to /usr/local/bin

Installed /home/steve/stratum-mining-proxy
Processing dependencies for stratum-mining-proxy==1.5.7
Searching for stratum>=0.2.15
Reading https://pypi.python.org/simple/stratum/
Best match: stratum 0.2.15
Downloading https://files.pythonhosted.org/packages/6d/e6/e7b45f24fd81d5511fbc37cad448d1b0784d85e4d0fb511a918a0c0e36c2/stratum-0.2.15.tar.gz#sha256=c09971cbfa136534de90d65221a71cde938c5ea96afe2943ed0e054e87cc18e3
Processing stratum-0.2.15.tar.gz
Writing /tmp/easy_install-Jwnt8w/stratum-0.2.15/setup.cfg
Running stratum-0.2.15/setup.py -q bdist_egg --dist-dir /tmp/easy_install-Jwnt8w/stratum-0.2.15/egg-dist-tmp-H2sRWn
Adding stratum 0.2.15 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/stratum-0.2.15-py2.7.egg
Searching for twisted>=12.2.0
Reading https://pypi.python.org/simple/twisted/
Best match: Twisted 18.9.0
Downloading https://files.pythonhosted.org/packages/5d/0e/a72d85a55761c2c3ff1cb968143a2fd5f360220779ed90e0fadf4106d4f2/Twisted-18.9.0.tar.bz2#sha256=294be2c6bf84ae776df2fc98e7af7d6537e1c5e60a46d33c3ce2a197677da395
Processing Twisted-18.9.0.tar.bz2
Writing /tmp/easy_install-kfcdDN/Twisted-18.9.0/setup.cfg
Running Twisted-18.9.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-kfcdDN/Twisted-18.9.0/egg-dist-tmp-fatokF
Checking .pth file support in .
/usr/bin/python -E -c pass
Searching for twisted>=16.4.0
Reading http://pypi.python.org/simple/twisted/
Couldn't find index page for 'twisted' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading http://pypi.python.org/simple/
No local packages or download links found for twisted>=16.4.0
error: Could not find suitable distribution for Requirement.parse('twisted>=16.4.0')

Testing to see if http://pypi.python.org/simple/twisted/ is even a thing we get: 
curl -v http://pypi.org/simple/twisted/
*   Trying 151.101.128.223...
* TCP_NODELAY set
* Connected to pypi.org (151.101.128.223) port 80 (#0)
> GET /simple/twisted/ HTTP/1.1
> Host: pypi.org
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 403 SSL is required
< Server: Varnish
< Retry-After: 0
< Content-Type: text/plain; charset=UTF-8
< Content-Length: 16
< Accept-Ranges: bytes
< Date: Sat, 01 Dec 2018 05:45:45 GMT
< Connection: close
< X-Served-By: cache-sea1022-SEA
< X-Cache: MISS
< X-Cache-Hits: 0
< X-Timer: S1543643146.919405,VS0,VE0
< Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
< X-Frame-Options: deny
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Permitted-Cross-Domain-Policies: none
< 
* Closing connection 0
SSL is required.

**Comment by pioruns** [comment]
Same here. Same errors, can't install this software on my Linux systems.
